[package]
name = "commie"
version = "0.1.0"
edition = "2021"
description = "A extremely simple cli command helper"

[dependencies]
colored = "3.0.0"
inquire = "0.7.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
